spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AbertoAndrade10/service-configuration 
          clone-on-start: true
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}

server:
  port: 8888

